#service apache2 start && npm run dev
if [ "${CODESPACES}" = "true" ]; then
    export APACHE_REVERS_ADRESS_8080=https://${CODESPACE_NAME}-8080.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}
    export APACHE_REVERS_ADRESS_8081=https://${CODESPACE_NAME}-8081.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}
    export APACHE_REVERS_ADRESS_8082=https://${CODESPACE_NAME}-8082.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}
    export APACHE_REVERS_ADRESS_8083=https://${CODESPACE_NAME}-8083.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}
    export APACHE_REVERS_ADRESS_8084=https://${CODESPACE_NAME}-8084.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}
    export APACHE_REVERS_ADRESS_8085=https://${CODESPACE_NAME}-8085.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}
    export APACHE_REVERS_ADRESS_8086=https://${CODESPACE_NAME}-8086.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}
    export APACHE_REVERS_ADRESS_8087=https://${CODESPACE_NAME}-8087.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}
    export APACHE_REVERS_ADRESS_8088=https://${CODESPACE_NAME}-8088.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}
else
    export APACHE_REVERS_ADRESS_8080=/
    export APACHE_REVERS_ADRESS_8081=/
    export APACHE_REVERS_ADRESS_8082=/
    export APACHE_REVERS_ADRESS_8083=/
    export APACHE_REVERS_ADRESS_8084=/
    export APACHE_REVERS_ADRESS_8085=/
    export APACHE_REVERS_ADRESS_8086=/
    export APACHE_REVERS_ADRESS_8087=/
    export APACHE_REVERS_ADRESS_8088=/
fi
apache2ctl start
npm run dev