name: Test

on: [push, pull_request]

jobs:
  dummy:
    name: "Dummy action"
    runs-on: ubuntu-24.04
    steps:
      - run: echo "hello world"
  deploy:
    name: "Test deploy"
    needs: dummy
    uses: fykosak/actions/.github/workflows/deploy.yml@master
    with:
      deploy-url: ${{ vars.DEPLOY_URL }}
    secrets:
      token: ${{ secrets.DEPLOY_TOKEN }}
